#!/usr/bin/env bash
# Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/ permanent;"
sudo sed -i "42i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
